# -*- coding: utf-8 -*-
"""japan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lSGkPv4hW7nyYfiLyehO6zBQslRt_P2l
"""

# Japan.py Travil

class OsakaPkg:
  def detail(self):
    print("[오사카] 유니버셜 패키지 100만원")