# -*- coding: utf-8 -*-
"""seoul.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M3bsGvZuU8sVTAVS69hqSjEM5QUnCHSJ
"""

# Seoul.py Travil

class SeoulPkg:
  def detail(self):
    print("[서울 도심 패키지] 호캉스 100만원")